services:
  app:
    build: .
    image: hilkim21/unilis-app:1.0
    container_name: unilis-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      # Keep vendor inside the container (don’t override with host)
      - /var/www/html/vendor
    depends_on:
      - db
    environment:
      DB_HOST: db
      MYSQL_USER: unilisuser
      MYSQL_PASSWORD: unilispass
      MYSQL_DATABASE: unilis

  db:
    image: mysql:8.0.33
    container_name: unilis-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: unilis
      MYSQL_USER: unilisuser
      MYSQL_PASSWORD: unilispass
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/unilis.sql:/docker-entrypoint-initdb.d/unilis.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: unilis-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass

volumes:
  db_data:
