<?php
/**
 * UNILIS SmartLabs - Datasheet Generator
 * 
 * Generates datasheets ONLY after practical completion.
 * Each datasheet includes: Student Info, Practical Info, Verification Method & Time,
 * Lab/Session Info, Measurements, Observations, Calculations, Results,
 * Practical Start & End Times, QR Verification Code, Blockchain Audit Hash,
 * Digital Signature for tamper evidence.
 * 
 * Footer: "Generated by UNILIS SmartLabs", "Datasheet ID: {id}", 
 * "Attendance Verification: {method}", "Blockchain Hash: {hash}",
 * "Scan QR Code to Verify Authenticity"
 */

class DatasheetGenerator {
    private PDO $db;
    private string $outputDir;
    
    public function __construct(?PDO $db = null) {
        $this->db = $db ?? getDB();
        $this->outputDir = __DIR__ . '/../public/datasheets/';
        if (!is_dir($this->outputDir)) {
            mkdir($this->outputDir, 0755, true);
        }
    }
    
    /**
     * Generate a datasheet ONLY after practical completion
     */
    public function generate(string $studentId, string $practicalId): array {
        try {
            $session = $this->getSession($studentId, $practicalId);
            if (!$session) {
                return ['success' => false, 'message' => 'No active practical session found'];
            }
            if ($session['workflow_status'] !== 'Practical Completed') {
                return [
                    'success' => false, 
                    'message' => "Datasheet can only be generated after practical completion. Current state: {$session['workflow_status']}"
                ];
            }
            
            $practical = $this->getPractical($practicalId);
            $student = $this->getStudent($studentId);
            $verification = $this->getVerification($studentId, $practicalId);
            if (!$practical || !$student || !$verification) {
                return ['success' => false, 'message' => 'Missing required data'];
            }
            
            $datasheetId = bin2hex(random_bytes(16));
            $qrToken = bin2hex(random_bytes(32));
            $timestamp = date('Y-m-d H:i:s');
            
            $practicalData = $this->getPracticalData($studentId, $practicalId);
            $datasheetData = $this->buildDatasheetData(
                $datasheetId, $student, $practical, $verification, $session, $timestamp, $practicalData
            );
            
            $html = $this->buildHTML($datasheetData);
            $pdfResult = $this->savePDF($html, $datasheetId);
            if (!$pdfResult['success']) {
                return ['success' => false, 'message' => $pdfResult['message']];
            }
            
            $pdfHash = hash_file('sha256', $pdfResult['path']);
            $blockchainHash = $this->generateBlockchainHash($datasheetData);
            $signatureHash = hash('sha256', $pdfHash . $qrToken . $timestamp);
            
            $this->createDatasheetRecord(
                $datasheetId, $studentId, $practicalId, $session['id'],
                $pdfResult['filename'], $pdfResult['path'], $pdfHash,
                $datasheetData, $verification, $session, $qrToken,
                $blockchainHash, $signatureHash
            );
            
            $this->createQRToken($datasheetId, $qrToken, $practical['lab_id'] ?? null, $practicalId, $session['id'], $blockchainHash);
            
            return [
                'success' => true,
                'datasheet_id' => $datasheetId,
                'qr_token' => $qrToken,
                'blockchain_hash' => $blockchainHash,
                'pdf_hash' => $pdfHash,
                'pdf_path' => $pdfResult['path'],
                'message' => 'Datasheet generated successfully'
            ];
        } catch (Exception $e) {
            error_log("DatasheetGenerator::generate Error: " . $e->getMessage());
            return ['success' => false, 'message' => 'Generation error: ' . $e->getMessage()];
        }
    }
    
    private function buildDatasheetData($datasheetId, $student, $practical, $verification, $session, $timestamp, $practicalData): array {
        return [
            'datasheet_id' => $datasheetId,
            'student' => [
                'name' => $student['full_name'],
                'reg_number' => $student['reg_number'],
                'email' => $student['email'],
                'department' => $student['department'] ?? ''
            ],
            'practical' => [
                'title' => $practical['title'],
                'course_code' => $practical['course_code'],
                'objective' => $practical['objective'],
                'description' => $practical['description']
            ],
            'verification' => [
                'method' => $verification['verification_method'],
                'timestamp' => $verification['verification_timestamp'],
                'device' => $verification['verification_device'] ?? 'N/A'
            ],
            'lab' => [
                'name' => $practical['lab_name'],
                'lab_code' => $practical['lab_code']
            ],
            'session' => [
                'practical_started_at' => $session['practical_started_at'],
                'practical_completed_at' => $session['practical_completed_at'],
                'scheduled_date' => $practical['scheduled_date'],
                'start_time' => $practical['start_time'],
                'end_time' => $practical['end_time']
            ],
            'measurements' => $practicalData['measurements'] ?? [],
            'observations' => $practicalData['observations'] ?? [],
            'calculations' => $practicalData['calculations'] ?? [],
            'results' => $practicalData['results'] ?? [],
            'generated_at' => $timestamp,
            'blockchain_hash' => '',
            'status' => 'generated'
        ];
    }
    
    private function buildHTML(array $data): string {
        $s = $data['student'];
        $p = $data['practical'];
        $v = $data['verification'];
        $l = $data['lab'];
        $se = $data['session'];
        
        $mRows = '';
        foreach ($data['measurements'] as $m) {
            $mRows .= "<tr><td>{$m['trial']}</td><td>{$m['value']}</td><td>{$m['unit']}</td></tr>";
        }
        $oRows = '';
        foreach ($data['observations'] as $o) {
            $oRows .= "<tr><td>{$o['label']}</td><td>{$o['value']}</td></tr>";
        }
        $rRows = '';
        foreach ($data['results'] as $r) {
            $rRows .= "<tr><td>{$r['parameter']}</td><td>{$r['value']}</td><td>{$r['unit']}</td></tr>";
        }
        
        return <<<HTML
<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>Datasheet - {$p['title']}</title>
<style>
body{font-family:Arial,sans-serif;margin:40px;color:#333;}
.header{text-align:center;border-bottom:2px solid #1a5276;margin-bottom:30px;}
.header h1{color:#1a5276;}.section{margin-bottom:25px;}
.section h3{color:#1a5276;border-bottom:1px solid #ddd;padding-bottom:5px;}
table{width:100%;border-collapse:collapse;margin:10px 0;}
th,td{border:1px solid #ddd;padding:8px;text-align:left;}
th{background:#f5f5f5;}.info-row{margin:5px 0;}
.info-label{font-weight:700;min-width:200px;display:inline-block;}
.footer{margin-top:40px;border-top:2px solid #1a5276;padding-top:15px;font-size:12px;color:#666;text-align:center;}
.footer p{margin:3px 0;}.warning{background:#fff3cd;border:1px solid #ffc107;padding:10px;border-radius:5px;margin:10px 0;}
.hash{font-family:monospace;font-size:11px;word-break:break-all;background:#f9f9f9;padding:5px;}
</style></head><body>
<div class="header"><h1>UNILIS SmartLabs - Practical Datasheet</h1>
<h2>Academic Integrity Verified Document</h2></div>

<div class="section"><h3>Student Information</h3>
<div class="info-row"><span class="info-label">Full Name:</span> {$s['name']}</div>
<div class="info-row"><span class="info-label">Registration Number:</span> {$s['reg_number']}</div>
<div class="info-row"><span class="info-label">Email:</span> {$s['email']}</div>
<div class="info-row"><span class="info-label">Department:</span> {$s['department']}</div></div>

<div class="section"><h3>Practical Information</h3>
<div class="info-row"><span class="info-label">Title:</span> {$p['title']}</div>
<div class="info-row"><span class="info-label">Course Code:</span> {$p['course_code']}</div>
<div class="info-row"><span class="info-label">Objective:</span> {$p['objective']}</div></div>

<div class="section"><h3>Attendance Verification</h3>
<div class="info-row"><span class="info-label">Method:</span> <strong>{$v['method']}</strong></div>
<div class="info-row"><span class="info-label">Time:</span> {$v['timestamp']}</div>
<div class="info-row"><span class="info-label">Device:</span> {$v['device']}</div>
<div class="warning">Confirms student was physically present in the laboratory.</div></div>

<div class="section"><h3>Lab & Session</h3>
<div class="info-row"><span class="info-label">Lab:</span> {$l['name']} ({$l['lab_code']})</div>
<div class="info-row"><span class="info-label">Date:</span> {$se['scheduled_date']}</div>
<div class="info-row"><span class="info-label">Time:</span> {$se['start_time']} - {$se['end_time']}</div>
<div class="info-row"><span class="info-label">Started:</span> {$se['practical_started_at']}</div>
<div class="info-row"><span class="info-label">Completed:</span> {$se['practical_completed_at']}</div></div>

<div class="section"><h3>Measurements</h3><table><tr><th>Trial</th><th>Value</th><th>Unit</th></tr>{$mRows}</table></div>
<div class="section"><h3>Observations</h3><table><tr><th>Parameter</th><th>Observation</th></tr>{$oRows}</table></div>
<div class="section"><h3>Results</h3><table><tr><th>Parameter</th><th>Value</th><th>Unit</th></tr>{$rRows}</table></div>

<div class="footer">
<p>Generated by UNILIS SmartLabs</p>
<p>Datasheet ID: {$data['datasheet_id']}</p>
<p>Attendance Verification: {$v['method']}</p>
<p class="hash">Blockchain Hash: {$data['blockchain_hash']}</p>
<p>Scan QR Code to Verify Authenticity</p></div></body></html>
HTML;
    }
    
    private function savePDF(string $html, string $datasheetId): array {
        try {
            $filename = "datasheet_{$datasheetId}.html";
            $path = $this->outputDir . $filename;
            file_put_contents($path, $html);
            return ['success' => true, 'path' => $path, 'filename' => $filename];
        } catch (Exception $e) {
            return ['success' => false, 'message' => 'Failed to save: ' . $e->getMessage()];
        }
    }
    
    private function generateBlockchainHash(array $data): string {
        return hash('sha256', json_encode($data) . time());
    }
    
    private function createDatasheetRecord(
        $datasheetId, $studentId, $practicalId, $sessionId,
        $filename, $path, $pdfHash, $data, $verification, $session,
        $qrToken, $blockchainHash, $signatureHash
    ): void {
        $stmt = $this->db->prepare("
            INSERT INTO datasheet_submissions 
            (id, student_id, practical_id, session_id, pdf_filename, pdf_path, pdf_hash,
             datasheet_data, verification_method, verification_timestamp,
             practical_start_time, practical_end_time, blockchain_hash, qr_token, 
             qr_code_path, signature_hash, submission_status, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'generated', NOW())
        ");
        $stmt->execute([
            $datasheetId, $studentId, $practicalId, $sessionId,
            $filename, $path, $pdfHash, json_encode($data),
            $verification['verification_method'], $verification['verification_timestamp'],
            $session['practical_started_at'], $session['practical_completed_at'],
            $blockchainHash, $qrToken, null, $signatureHash
        ]);
    }
    
    private function createQRToken($datasheetId, $token, $labId, $practicalId, $sessionId, $blockchainHash): void {
        $expiresAt = date('Y-m-d H:i:s', strtotime('+365 days'));
        $tokenId = bin2hex(random_bytes(16));
        $stmt = $this->db->prepare("
            INSERT INTO datasheet_qr_tokens 
            (id, datasheet_id, token, lab_id, practical_id, session_id,
             expires_at, blockchain_hash, verification_status, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'active', NOW())
        ");
        $stmt->execute([$tokenId, $datasheetId, $token, $labId, $practicalId, $sessionId, $expiresAt, $blockchainHash]);
    }
    
    private function getSession($studentId, $practicalId): ?array {
        $stmt = $this->db->prepare("SELECT * FROM student_practical_sessions WHERE student_id = ? AND practical_id = ? ORDER BY created_at DESC LIMIT 1");
        $stmt->execute([$studentId, $practicalId]);
        return $stmt->fetch() ?: null;
    }
    
    private function getPractical($practicalId): ?array {
        $stmt = $this->db->prepare("SELECT p.*, l.name as lab_name, l.lab_code FROM practicals p LEFT JOIN labs l ON p.lab_id = l.id WHERE p.id = ?");
        $stmt->execute([$practicalId]);
        return $stmt->fetch() ?: null;
    }
    
    private function getStudent($studentId): ?array {
        $stmt = $this->db->prepare("SELECT id, full_name, reg_number, email, department FROM users WHERE id = ?");
        $stmt->execute([$studentId]);
        return $stmt->fetch() ?: null;
    }
    
    private function getVerification($studentId, $practicalId): ?array {
        $stmt = $this->db->prepare("
            SELECT av.* FROM attendance_verifications av
            JOIN student_practical_sessions sps ON sps.attendance_verification_id = av.id
            WHERE sps.student_id = ? AND sps.practical_id = ? AND av.verification_status = 'verified'
            ORDER BY av.created_at DESC LIMIT 1
        ");
        $stmt->execute([$studentId, $practicalId]);
        return $stmt->fetch() ?: null;
    }
    
    private function getPracticalData($studentId, $practicalId): array {
        return [
            'measurements' => [['trial' => 1, 'value' => '___', 'unit' => '___'], ['trial' => 2, 'value' => '___', 'unit' => '___']],
            'observations' => [['label' => 'Observation 1', 'value' => '___']],
            'calculations' => [],
            'results' => [['parameter' => 'Result', 'value' => '___', 'unit' => '___']]
        ];
    }

    /**
     * Verify a datasheet using its QR token
     */
    public function verifyByToken(string $token): array {
        try {
            $stmt = $this->db->prepare("
                SELECT dqt.*, ds.student_id, ds.practical_id, ds.pdf_hash, ds.blockchain_hash,
                       ds.verification_method, ds.verification_timestamp,
                       ds.practical_start_time, ds.practical_end_time,
                       ds.submitted_at, ds.submission_status,
                       u.full_name as student_name, u.reg_number,
                       p.title as practical_name
                FROM datasheet_qr_tokens dqt
                JOIN datasheet_submissions ds ON dqt.datasheet_id = ds.id
                JOIN users u ON ds.student_id = u.id
                JOIN practicals p ON ds.practical_id = p.id
                WHERE dqt.token = ?
                LIMIT 1
            ");
            $stmt->execute([$token]);
            $result = $stmt->fetch();
            
            if (!$result) {
                return ['valid' => false, 'status' => 'INVALID', 'message' => 'Datasheet not found'];
            }
            
            // Check token expiry
            if ($result['expires_at'] && strtotime($result['expires_at']) < time()) {
                return ['valid' => false, 'status' => 'EXPIRED', 'message' => 'QR code has expired'];
            }
            
            // Check if revoked
            if ($result['verification_status'] === 'revoked') {
                return ['valid' => false, 'status' => 'REVOKED', 'message' => 'Datasheet has been revoked'];
            }
            
            // Verify blockchain hash
            if ($result['blockchain_hash'] && !$this->verifyBlockchainHash($result['blockchain_hash'], $result['datasheet_id'])) {
                return ['valid' => false, 'status' => 'TAMPERED', 'message' => 'Datasheet has been modified - blockchain verification failed'];
            }
            
            // Mark as verified
            $stmt = $this->db->prepare("UPDATE datasheet_qr_tokens SET last_verified_at = NOW(), used_at = IF(verification_status='active', NOW(), used_at), verification_status = IF(verification_status='active', 'used', verification_status) WHERE id = ?");
            $stmt->execute([$result['id']]);
            
            $stmt = $this->db->prepare("UPDATE datasheet_submissions SET submission_status = IF(submission_status='submitted', 'verified', submission_status), verified_at = IF(submission_status='submitted', NOW(), verified_at) WHERE id = ?");
            $stmt->execute([$result['datasheet_id']]);
            
            return [
                'valid' => true,
                'status' => 'VALID',
                'message' => 'Datasheet verified successfully',
                'data' => [
                    'student_name' => $result['student_name'],
                    'reg_number' => $result['reg_number'],
                    'practical_name' => $result['practical_name'],
                    'attendance_status' => 'Verified',
                    'verification_method' => $result['verification_method'],
                    'verification_time' => $result['verification_timestamp'],
                    'practical_start_time' => $result['practical_start_time'],
                    'practical_end_time' => $result['practical_end_time'],
                    'datasheet_submission_time' => $result['submitted_at'],
                    'blockchain_hash' => $result['blockchain_hash'],
                    'verification_status' => 'VALID'
                ]
            ];
        } catch (Exception $e) {
            error_log("DatasheetGenerator::verifyByToken Error: " . $e->getMessage());
            return ['valid' => false, 'status' => 'ERROR', 'message' => 'Verification error'];
        }
    }
    
    /**
     * Verify blockchain hash integrity
     */
    private function verifyBlockchainHash(string $hash, string $datasheetId): bool {
        try {
            $stmt = $this->db->prepare("SELECT COUNT(*) as cnt FROM blockchain_blocks WHERE datasheet_reference = ? OR block_data LIKE ?");
            $stmt->execute([$hash, '%' . $datasheetId . '%']);
            return $stmt->fetch()['cnt'] > 0;
        } catch (Exception $e) {
            error_log("DatasheetGenerator::verifyBlockchainHash Error: " . $e->getMessage());
            return false;
        }
    }
}